#!/usr/bin/env node
/**
 * Optimize images for GitHub Pages: small files, no quality compromise, progressive loading.
 * - Gallery assets: AVIF (primary) + JPEG (fallback) for display (800w) and full (1600w).
 *   AVIF is the canonical manifest reference. Placeholders are also AVIF.
 * - Hero carousel images are generated by the gallery manager publish flow (not here).
 * Run before build: npm run optimize-images
 * After generating outputs, removes files under public/images/ that are not referenced
 * from src/ (including gallery.manifest.yaml), unless you pass --no-prune.
 */
import sharp from "sharp";
import { readdir, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { pruneUnusedOptimizedImages } from "./clean-unused-optimized-images.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const siteRoot = join(__dirname, "..");
const publicDir = join(siteRoot, "public", "images");

const AVIF_DISPLAY = { quality: 60, effort: 4 };
const AVIF_FULL = { quality: 60, effort: 4 };
const AVIF_PLACEHOLDER = { quality: 60, effort: 2 };
const JPEG_DISPLAY = { quality: 80, progressive: true, mozjpeg: true };
const JPEG_FULL = { quality: 80, progressive: true, mozjpeg: true };
const FULL_MAX_WIDTH = 1600;

function baseName(file) {
  return file.replace(/\.(jpe?g)$/i, "");
}

async function ensureDir(p) {
  await mkdir(p, { recursive: true });
}

async function main() {
  console.log("Optimizing images…");

  const assetsDir = join(publicDir, "assets");

  // Gallery: AVIF + JPEG for display/full/placeholders
  const displayDir = join(publicDir, "gallery", "display");
  const placeholdersDir = join(publicDir, "gallery", "placeholders");
  const fullDir = join(publicDir, "gallery", "full");
  await ensureDir(displayDir);
  await ensureDir(placeholdersDir);
  await ensureDir(fullDir);

  let files = [];
  try {
    files = (await readdir(assetsDir))
      .filter((f) => /\.(jpe?g)$/i.test(f))
      .filter((f) => f !== "base");
  } catch {
    // no assets
  }

  for (const file of files) {
    const src = join(assetsDir, file);
    const base = baseName(file);
    try {
      const pipeline = sharp(src, { failOnError: false });
      const meta = await pipeline.metadata();
      const w = meta.width || 800;

      // Display (800w): AVIF + JPEG
      const displayResize = sharp(src, { failOnError: false }).rotate().resize(Math.min(800, w));
      await displayResize.clone().avif(AVIF_DISPLAY).toFile(join(displayDir, `${base}.avif`));
      await displayResize.clone().jpeg(JPEG_DISPLAY).toFile(join(displayDir, `${base}.jpg`));

      // Placeholder (40w): AVIF (tiny blur-up)
      await sharp(src, { failOnError: false })
        .rotate()
        .resize(40)
        .avif(AVIF_PLACEHOLDER)
        .toFile(join(placeholdersDir, `${base}.avif`));

      // Full (1600w): AVIF + JPEG
      const fullResize = sharp(src, { failOnError: false }).rotate().resize(Math.min(FULL_MAX_WIDTH, w));
      await fullResize.clone().avif(AVIF_FULL).toFile(join(fullDir, `${base}.avif`));
      await fullResize.clone().jpeg(JPEG_FULL).toFile(join(fullDir, `${base}.jpg`));

      console.log(" ", file, "→ display (.avif+.jpg) + placeholder (.avif) + full (.avif+.jpg)");
    } catch (e) {
      console.warn("  ", file, e.message);
    }
  }

  // 3. Sponsors: convert cataj.png to WebP for smaller transfer (Lighthouse)
  const sponsorsDir = join(publicDir, "sponsors");
  const catajPng = join(sponsorsDir, "cataj.png");
  const catajWebp = join(sponsorsDir, "cataj.webp");
  try {
    if (existsSync(catajPng)) {
      await sharp(catajPng).webp({ quality: 90, effort: 4 }).toFile(catajWebp);
      console.log("  sponsors: cataj.png → cataj.webp");
    }
  } catch (e) {
    console.warn("  sponsors cataj:", e.message);
  }

  if (!process.argv.includes("--no-prune")) {
    const { removed } = pruneUnusedOptimizedImages(siteRoot, { dryRun: false });
    if (removed > 0) {
      console.log(
        `  Pruned ${removed} file(s) not referenced in src/ (manifest + code).`,
      );
    }
  }

  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
